platform :ios, '10.0'

target 'Jogger' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Swinject', '~> 2.1.0'
  pod 'SwinjectAutoregistration', '2.1.0'
  pod 'SwinjectStoryboard', '1.1.1'

  target 'JoggerTests' do
    inherit! :search_paths

    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Database'

  end

  target 'JoggerUITests' do
    inherit! :search_paths

    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Database'

  end

end
