platform :ios, '10.0'

target 'Jogger' do
  use_frameworks!

  pod 'Firebase/Core'

  target 'JoggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JoggerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
