platform :ios, '10.0'

target 'Jogger' do
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Swinject', '~> 2.1.0'

  target 'JoggerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JoggerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
